[package]
name = "sad-monte-carlo"
version = "0.1.0"
authors = ["David Roundy <roundyd@oregonstate.edu>"]

[lib]
name = "sadmc"
path = "src/lib.rs"

[dependencies]

dimensioned = { git = "https://github.com/paholg/dimensioned", features=["serde"] }
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
clapme = "0.1.2"

vector3d = "0.1.1"
rand_core = "0.2.1"
rand = "0.5.4"

[features]
# Treat warnings as a build error.
strict = []
